#!/usr/bin/env bash
getXresColor() { 
    xrdb -query | grep "${1}:" | grep -oE '#[a-zA-Z0-9]{6}' | cut -c 1-
}

initBSPWM() {
    bspc config border_width          2
    bspc config window_gap            5
    bspc config split_ratio           0.5
    bspc config borderless_monocle    true
    bspc config gapless_monocle       true
    bspc config focus_follows_pointer false || true
    bspc config click_to_focus        button1

    bspc config normal_border_color   `getXresColor base00`
    bspc config focused_border_color  `getXresColor base05`
    bspc config active_border_color   `getXresColor base03`
    bspc config presel_feedback_color `getXresColor base0A`
    
    bspc rule -a "Spotify" desktop=^5
    bspc rule -a "Chromium-browser:crx_eggkanocgddhmamlbiijnphhppkpkmkl" state=floating
    bspc rule -a "mpv" state=floating
    
    local desktops_per_mon=5

    local oldM=$(bspc query -M)
    local mons=$(randrq -f '{{.Name}}:{{.Width}}x{{.Height}}')

    local x=0
    for m in ${mons}; do
        local name="${m%:*}"
        local mode="${m#*:}"

        xrandr --output "${name}" --mode "${mode}" --pos ${x}x0
        
        bspc wm -a "${name}" "${mode}+${x}+0"

        local names=()
        for j in `seq $desktops_per_mon`; do
            names+=("$name/$j")
        done
    
        bspc monitor "$name" -d ${names[@]}

        x=$((${x}+${mode%x*}))
    done

    for m in ${oldM}; do
        local first="`head -1 <<< ${mons} | cut -d':' -f1`/1"
        for n in `bspc query -N -m "${m}"`; do
            bspc node "${n}" -d ${first}
        done
        for d in `bspc query -D -m "${m}"`; do
            bspc desktop "${d}" -r
        done
        bspc monitor "${m}" -r
    done

    systemctl --user restart polybar
    feh --bg-fill "$HOME/pictures/wp"
}

initBSPWM
