version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/.github/actions/build-nix"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/.github/actions/install-nix"
  schedule:
    interval: "daily"
