#!/bin/sh

source $(dirname $0)/config

sxhkd &

bspc config border_width            2
bspc config window_gap              7

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config focus_follows_pointer   false
bspc config click_to_focus          true
bspc config presel_feedback_color   ${BG}
bspc config normal_frame_opacity    0.0
bspc config focused_frame_opacity   0.1

display_names=( I II III IV V VI VII VIII IX X )
monitors=( `bspc query -M | tr '\n' ' '` )

displays_per_mon=`echo "${#display_names[@]}/${#monitors[@]}" | bc`

for i in ${!monitors[@]}; do
    start_index=`echo "$i*$displays_per_mon" | bc`
    end_index=`echo "$start_index+$displays_per_mon" | bc`
    bspc monitor ${monitors[$i]} -d ${display_names[@]:$start_index:$end_index}
done

$(dirname $0)/panel &
