#!/usr/bin/env sh

source $(dirname `readlink -f $0`)/config

sxhkd &

max_displays=10

monitors=( `bspc query -M | tr '\n' ' '` )
displays_per_mon=`echo "$max_displays/${#monitors[@]}" | bc`

for i in ${!monitors[@]}; do
    monitor=${monitors[$i]} 

    let i++

    names=()
    for j in `seq $displays_per_mon`; do
        names+=("$i/$j")
    done
    bspc monitor $monitor -n $i -d ${names[@]}
    bspc desktop $i/1 -l monocle
done

bspc config border_width            1
bspc config window_gap              6

bspc config                  split_ratio  0.60
bspc config           borderless_monocle  true
bspc config              gapless_monocle  true
bspc config        focus_follows_pointer  false
bspc config               click_to_focus  true
bspc config          normal_border_color  ${FG}
bspc config         focused_border_color  ${BLUE}
bspc config          active_border_color  ${BLUE2}
bspc config        presel_feedback_color  ${BG}

bspc rule -a "Spotify" desktop=^5
bspc rule -a "Chromium-browser:crx_eggkanocgddhmamlbiijnphhppkpkmkl" state=floating
bspc rule -a "mpv" state=floating

polybar top&
