#!/usr/bin/env sh

source $(dirname $0)/config

sxhkd &

max_displays=10

monitors=( `bspc query -M | tr '\n' ' '` )
displays_per_mon=`echo "$max_displays/${#monitors[@]}" | bc`

for i in ${!monitors[@]}; do
    monitor=${monitors[$i]} 

    let i++

    names=()
    for j in `seq $displays_per_mon`; do
        names+=("$i/$j")
    done
    bspc monitor $monitor -n $i -d ${names[@]}
done

bspc config border_width            1
bspc config window_gap              7

bspc config                  split_ratio  0.60
bspc config           borderless_monocle  true
bspc config              gapless_monocle  true
bspc config        focus_follows_pointer  false
bspc config               click_to_focus  true
bspc config          normal_border_color  ${FG}
bspc config         focused_border_color  ${BLUE}
bspc config          active_border_color  ${BLUE2}
bspc config        presel_feedback_color  ${BG}

max_displays=10

monitors=( `bspc query -M | tr '\n' ' '` )
displays_per_mon=`echo "$max_displays/${#monitors[@]}" | bc`

$(dirname $0)/panel &
