#! /bin/sh
sxhkd &

max_displays=10

monitors=( `bspc query -M | tr '\n' ' '` )
displays_per_mon=`echo "$max_displays/${#monitors[@]}" | bc`

for i in ${!monitors[@]}; do
    monitor=${monitors[$i]} 

    let i++

    names=()
    for j in `seq $displays_per_mon`; do
        names+=("$i/$j")
    done
    bspc monitor $monitor -n $i -d ${names[@]}
done


BW=2

bspc config                   window_gap  -$BW
bspc config                 border_width  $BW
for side in right bottom left ; do
	bspc config          ${side}_padding  $BW
done


bspc config                  split_ratio  0.50
bspc config           borderless_monocle  true
bspc config              gapless_monocle  true
bspc config        focus_follows_pointer  false
bspc config               click_to_focus  true
bspc config          normal_border_color  "#333333"
bspc config          active_border_color  "#2d2d2d"
bspc config         focused_border_color  "#2d2d2d"

wmname "LG3D" #compatibility issues fix
#panel &

#tint2 &
# sudo wpa_gui -t &
# termite -e tmux -t TMUX &
