#! /bin/sh
PANEL_FIFO=/tmp/panel-fifo

HEIGHT=24
FONT="Fira Sans"
FONT_ICON="Hurmit"
#FONT_ICON="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
WM_NAME="Bspwm"

# icons
CSTART="\ue00d"
CSOUND="\ue04d"
CVOLUME="\ue11b"
CMAIL="\ue070"
CRAM="\ue19a"
CCPU="\ue1c1"
CNET="\ue04b"
CWIFI="\ue222"
CFULL="\ue056"
CNONE="\ue0e6"
CCLOCK="\ue016"
CTIME="\ue018"
CPACK="\ue1b7"
# icons panel music
CPREV="\ue055"
CNEXT="\ue05b"
CPLAY="\ue058"
CPAUS="\ue059"
# battery or AC
BAT100="\ue254"
BAT70="\ue252"
BAT50="\ue250"
BAT30="\ue24f"
BAT15="\ue24e"
BAT7="\ue24c"
CAC="\ue215"

# $(pAction ${fg} ${bg} ${command} ${whatprint})
pAction() {
    echo -n "%{F$1}%{B$2}%{A:$3:}$(printf '%b' $4)%{A}%{B-}%{F-}"
}

# $(pIcon ${color} ${icon})
pIcon() {
    echo -n "%{F$1}$(printf '%b' $2)%{F-}"
}

# $(pText ${color} ${text})
pText() {
    echo -n "%{F$1}$2%{F-}"
}

getXresColor() {
   echo "$( xrdb -query | grep $1: | grep -oE '#[a-zA-Z0-9]{6}' | cut -c 1- )"
}

# colors
BLACK="$(getXresColor color0)"
BLACK2="$(getXresColor color8)"
RED="$(getXresColor color1)"
RED2="$(getXresColor color9)"
GREEN="$(getXresColor color2)"
GREEN2="$(getXresColor color10)"
YELLOW="$(getXresColor color3)"
YELLOW2="$(getXresColor color11)"
BLUE="$(getXresColor color4)"
BLUE2="$(getXresColor color12)"
MAGENTA="$(getXresColor color5)"
MAGENTA2="$(getXresColor color13)"
CYAN="$(getXresColor color6)"
CYAN2="$(getXresColor color14)" 
WHITE="$(getXresColor color7)"
WHITE2="$(getXresColor color15)"

BG="$(getXresColor background)"
FG="$(getXresColor foreground)"

SEP=" "
