#! /bin/sh
PANEL_FIFO=/tmp/panel-fifo

HEIGHT=24
#FONT="Fira Sans"
FONT="Fira"
FONT_ICON="FontAwesome"
WM_NAME="Bspwm"

# icons

# $(faToUtf ${faIcon})
faToUtf() {
    echo -n "\x$(echo ${1} | hexdump -C | head -1 | cut -d' ' -f3,4,5 | sed 's: :\\x:g')"
}

CSTART="$(faToUtf )"

#CFULL="$(faToUtf )"
#CNONE="$(faToUtf )"
CFULL="$(faToUtf )"
CNONE="$(faToUtf )"

CSOUND="$(faToUtf )"
CVOLUME="$(faToUtf )"

CPREV="$(faToUtf )"
CNEXT="$(faToUtf )"
CPLAY="$(faToUtf )"
CPAUS="$(faToUtf )"

CCLOCK="$(faToUtf )"
CDATE="$(faToUtf )"
CMAIL="$(faToUtf )"

CRAM="$(faToUtf )"
CCPU="$(faToUtf )"
CNET="$(faToUtf )"
CWIFI="$(faToUtf )"

BAT100="$(faToUtf  )"
BAT75="$(faToUtf )"
BAT50="$(faToUtf  )"
BAT25="$(faToUtf )"
BAT0="$(faToUtf )"
CAC="$(faToUtf )"

# $(pAction ${fg} ${bg} ${command} ${whatprint})
pAction() {
    echo -n "%{F$1}%{B$2}%{A:$3:}$(printf '%b' $4)%{A}%{B-}%{F-}"
}

# $(pIcon ${color} ${icon})
pIcon() {
    echo -n "%{F$1}$(printf '%b' $2)%{F-}"
}

# $(pText ${color} ${text})
pText() {
    echo -n "%{F$1}$2%{F-}"
}

# $(getXresColor ${colorName})
getXresColor() {
   echo "$(xrdb -query | grep $1: | grep -oE '#[a-zA-Z0-9]{6}' | cut -c 1- )"
}

# colors
BLACK="$(getXresColor color0)"
BLACK2="$(getXresColor color8)"
RED="$(getXresColor color1)"
RED2="$(getXresColor color9)"
GREEN="$(getXresColor color2)"
GREEN2="$(getXresColor color10)"
YELLOW="$(getXresColor color3)"
YELLOW2="$(getXresColor color11)"
BLUE="$(getXresColor color4)"
BLUE2="$(getXresColor color12)"
MAGENTA="$(getXresColor color5)"
MAGENTA2="$(getXresColor color13)"
CYAN="$(getXresColor color6)"
CYAN2="$(getXresColor color14)" 
WHITE="$(getXresColor color7)"
WHITE2="$(getXresColor color15)"

BG="$(getXresColor background)"
FG="$(getXresColor foreground)"

SEP=" "
