#!/bin/sh

display_names=( I II III IV V VI VII VIII IX X )
monitors=( `bspc query -M | tr '\n' ' '` )

displays_per_mon=`echo "${#display_names[@]}/${#monitors[@]}" | bc`

for i in ${!monitors[@]}; do
    start_index=`echo "$i*$displays_per_mon" | bc`
    end_index=`echo "$start_index+$displays_per_mon" | bc`
    echo bspc monitor ${monitors[$i]} -d ${display_names[@]:$start_index:$end_index}
done
