name: install Nix

inputs:
  cachixAuthToken:
    description: auth token for https://app.cachix.org/organization/rvolosatovs/cache/rvolosatovs

runs:
  using: composite
  steps:
  - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
    with:
      extra-conf: |
        accept-flake-config = true

  - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

  - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
    continue-on-error: true
    with:
      name: rvolosatovs
      authToken: '${{ inputs.cachixAuthToken }}'
