_: final: prev: {
  # Everything `rtk init` writes for each supported agent, generated by the rtk
  # binary itself so it tracks the installed rtk version rather than being
  # vendored.
  rtk-init = final.runCommand "rtk-init" { nativeBuildInputs = [ final.rtk ]; } ''
    export HOME="$out"
    mkdir -p "$out/.claude" "$out/.codex" "$out/.gemini" "$out/.cursor"
    cd "$out"

    rtk init --agent claude -g --auto-patch
    rtk init --copilot -g
    rtk init --gemini -g --auto-patch
    rtk init --codex -g
    rtk init --agent cursor -g
    rtk init --agent windsurf -g
    rtk init --agent cline -g
    rtk init --agent kilocode
    rtk init --agent antigravity
    rtk init --agent hermes -g
  '';
}
