name: Build
on: [ push, pull_request ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        output:
        - nixosConfigurations.rvolosatovs-dev.config.system.build.toplevel

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v21
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: rvolosatovs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - uses: cachix/cachix-action@v12
      with:
        name: nix-community

    - uses: cachix/cachix-action@v12
      with:
        name: enarx
    - uses: cachix/cachix-action@v12
      with:
        name: wasmcloud

    - name: Build ${{ matrix.output }}
      run: nix build -L --show-trace '.#${{ matrix.output }}'

    # TODO: Build and run a VM, test
