name: check

on:
  schedule:
  - cron: '0 10 * * *'
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        platform:
        - host: macos-latest
        - host: ubuntu-latest
    runs-on: ${{ matrix.platform.host }}
    steps:
    - name: Remove unused files
      if: ${{ runner.os == 'Linux' }}
      # based on https://dev.to/mathio/squeezing-disk-space-from-github-actions-runners-an-engineers-guide-3pjg
      run: |
        sudo rm -rf /usr/lib/jvm
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /opt/microsoft /opt/google
        sudo rm -rf /opt/az
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /opt/hostedtoolcache

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: ./.github/actions/install-nix
      with:
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L
    - if: github.event_name == 'push' && runner.os == 'macOS'
      run: nix build -L .#darwinConfigurations.iridium.system
    - if: github.event_name == 'push' && runner.os == 'Linux'
      run: |
        nix build -L .#nixosConfigurations.cobalt.config.system.build.toplevel
        nix build -L .#nixosConfigurations.osmium.config.system.build.toplevel

    # TODO: Run a VM, test
