name: dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.actor == 'rvolosatovs-bot[bot]'
    runs-on: ubuntu-latest
    steps:
    - run: gh pr merge --auto --rebase "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
