name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nix-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ./.github/actions/install-nix
        with: 
          cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: jessestricker/nix-flake-update@v1
        id: nix-update
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: nix-update
          commit-message: "build(nix): update flake lock"
          title: "build(nix): update flake lock"
          body: ${{ steps.nix-update.outputs.pull-request-body }}
          labels: dependencies, nix
          assignees: |
            rvolosatovs
          signoff: true
