name: nix-flake-update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    steps:
      - uses: rvolosatovs/nix-flake-update-action@v2.0.1-rc.2
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          assignees: rvolosatovs
          reviewers: rvolosatovs
          delete-branch: true
          signoff: true
          labels: dependencies
